# Настройки VK API
longpoll:
  # Токен доступа
  token: TOKEN
  # Версия
  version: 5.131

# Настройки логирования
logging:
  # Запись логов в файл
  log_to_file: false

# Основные настройки
general:
  # ID бесед, в которых бот активен
  # Чтобы бот работал везде поставьте значение <<all>>
  active_chats: all
  # ID пользователей, на чьи сообщения отвечать
  # Чтобы бот отвечал на все поставьте значение <<all>>
  users_ids: all
  # ID пользователей, чьи сообщения игнорировать [ОБЯЗАТЕЛЬНО ВПИШИТЕ ID СТРАНИЦЫ, НА КОТОРОМ СТОИТ БОТ, ИНАЧЕ ОН БУДЕТ СПАМИТЬ!]
  ignore_ids: [123]
  # Сообщение пользователям, которые есть в списке
  message: 'Иди кушать, мама зовет!'