# Настройки VK API
longpoll:
  # Токен доступа
  token: TOKEN
  # Версия
  version: 5.131
  # ID пользователя, на котором стоит бот
  id: ID

# Настройки логирования
logging:
  # Запись логов в файл
  log_to_file: false

# Основные настройки
general:
  # ID бесед, в которых бот активен
  # Чтобы бот работал везде поставьте значение <<all>>
  active_chats: all
  # ID пользователей, на чьи сообщения отвечать
  # Чтобы бот отвечал на все поставьте значение <<all>>
  users_ids: all
  # Сообщение пользователям, которые есть в списке
  message: 'Иди кушать, мама зовет!'